modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/przxmus/nick-hider/issues"
license = "GNU Affero General Public License v3.0"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL = "https://github.com/przxmus/nick-hider"
logoFile = "assets/${id}/icon.png"
authors = "przxmus"
displayTest = "IGNORE_ALL_VERSION"
description = '''
${description}
'''

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersion},)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "${id}.mixins.json"
