modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/przxmus/nick-hider/issues"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "przxmus"
displayTest = "IGNORE_ALL_VERSION"
description = '''
${description}
'''

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "${id}.mixins.json"
