modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/przxmus/nick-hider/issues"
license = "GNU Affero General Public License v3.0"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
logoFile = "assets/${id}/icon.png"
authors = "przxmus"
description = '''
${description}
'''

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "CLIENT"
